org: gabicardetti
app: basecamp
service: basecamp

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  hello:
    handler: ./src/handler.hello
    events:
     - http:
        path: basecamp
        method: post
        cors: true

plugins:
  - serverless-webpack

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js 
    # includeModules: true